#!/usr/bin/env bash
# scripts/install-vpn.sh — Installs and configures OpenVPN + Easy-RSA
set -euo pipefail
source /etc/openvpn-panel/install.conf

log()  { echo -e "\033[0;32m[✔]\033[0m $*"; }
info() { echo -e "\033[0;34m[→]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }

# ── Install packages ──────────────────────────────────────────────────────────
info "Installing OpenVPN and Easy-RSA..."
apt-get install -y -qq openvpn easy-rsa

# ── TUN device check ──────────────────────────────────────────────────────────
if [ ! -c /dev/net/tun ]; then
  warn "TUN device not found — creating..."
  mkdir -p /dev/net
  mknod /dev/net/tun c 10 200
  chmod 600 /dev/net/tun
fi
log "TUN device available"

# ── PKI Setup ─────────────────────────────────────────────────────────────────
PKI_DIR=/etc/openvpn/easy-rsa

if [ ! -d "$PKI_DIR/pki" ]; then
  info "Initialising PKI..."
  make-cadir "$PKI_DIR"
  cd "$PKI_DIR"

  # Write vars
  cat > vars << VARS
set_var EASYRSA_REQ_COUNTRY    "US"
set_var EASYRSA_REQ_PROVINCE   "CA"
set_var EASYRSA_REQ_CITY       "SanFrancisco"
set_var EASYRSA_REQ_ORG        "${ORG_NAME}"
set_var EASYRSA_REQ_EMAIL      "admin@vpn.local"
set_var EASYRSA_REQ_OU         "VPN"
set_var EASYRSA_KEY_SIZE       4096
set_var EASYRSA_CA_EXPIRE      3650
set_var EASYRSA_CERT_EXPIRE    825
set_var EASYRSA_DIGEST         "sha256"
VARS

  ./easyrsa init-pki          < /dev/null
  ./easyrsa build-ca nopass   < /dev/null
  ./easyrsa gen-req server nopass < /dev/null
  echo "yes" | ./easyrsa sign-req server server
  ./easyrsa gen-dh
  ./easyrsa gen-crl
  openvpn --genkey secret /etc/openvpn/ta.key
  log "PKI initialised"
else
  warn "PKI already exists — skipping"
fi

# ── Detect outbound interface ─────────────────────────────────────────────────
EXT_IF=$(ip route show default | awk '/default/ {print $5}' | head -1)
info "External interface: $EXT_IF"

# ── Server config ─────────────────────────────────────────────────────────────
info "Writing server.conf..."
cat > /etc/openvpn/server.conf << CONF
# =============================================================
#  OpenVPN Server — Generated by openvpn-panel installer
#  Date: $(date -Iseconds)
# =============================================================

port ${VPN_PORT}
proto udp
dev tun

# Certificates
ca   /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key  /etc/openvpn/easy-rsa/pki/private/server.key
dh   /etc/openvpn/easy-rsa/pki/dh.pem
crl-verify /etc/openvpn/easy-rsa/pki/crl.pem

# TLS auth (HMAC firewall)
tls-auth /etc/openvpn/ta.key 0
key-direction 0

# Network
server ${VPN_SUBNET} 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 8.8.8.8"
ifconfig-pool-persist /var/log/openvpn/ipp.txt

# TP-Link compatible cipher
cipher ${DEFAULT_CIPHER}
auth SHA256
tls-version-min 1.2
tls-cipher TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-GCM-SHA384

# Hardening
user nobody
group nogroup

# Performance
keepalive 10 120
persist-key
persist-tun
explicit-exit-notify 1

# Logging
status /var/log/openvpn/status.log 10
log-append /var/log/openvpn/openvpn.log
verb 3
CONF

# ── IP forwarding ─────────────────────────────────────────────────────────────
echo 1 > /proc/sys/net/ipv4/ip_forward
grep -q 'net.ipv4.ip_forward=1' /etc/sysctl.conf \
  || echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

# ── NAT ───────────────────────────────────────────────────────────────────────
iptables -t nat -C POSTROUTING -s "${VPN_SUBNET}/24" -o "$EXT_IF" -j MASQUERADE 2>/dev/null \
  || iptables -t nat -A POSTROUTING -s "${VPN_SUBNET}/24" -o "$EXT_IF" -j MASQUERADE
netfilter-persistent save 2>/dev/null || true
log "NAT configured on $EXT_IF"

# ── Log dir ───────────────────────────────────────────────────────────────────
mkdir -p /var/log/openvpn
chown nobody:nogroup /var/log/openvpn 2>/dev/null || true

# ── Systemd ───────────────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl enable openvpn@server
systemctl restart openvpn@server
sleep 2
systemctl is-active openvpn@server \
  && log "OpenVPN is running on port ${VPN_PORT}/UDP" \
  || (journalctl -u openvpn@server -n 20 --no-pager; exit 1)
